### ISSUE TITLE
rebase NON interattivo

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#10]
ora facciamo il rebase (non interattivo, quindi **senza** -i)

cominciamo a fare il rebase di memory. Lo vogliamo accodare a master.

``` bash
$ git checkout memory
$ git rebase master
```

qui ti darà degli errori perché tutti e due i rami modificano main.c
Prova un

``` bash
$ git status
```

Aggiusta il file main.c (attento, è incasinato)

``` bash
$ git add main.c
$ git rebase --continue
```

Qui dovrebbe darti problemi un'altra volta perché i commit sono due su memory
Rimodifica main.c (stavolta dovrebbe essere un po' piu' semplice) e quindi

``` bash
$ git add main.c
$ git rebase --continue
```

Ora dovrebbe andare.
Guardati il log e fai push forzato

**Comment by TeoColuccio** [comment]
Stranamente ho fatto git add main.c e poi rebase --continue e dava gli
stessi errori di prima. così ho provato git add . e poi continue ed ha
funzionato

2015-12-29 23:59 GMT+01:00 Fabio Z Tessitore notifications@github.com:
