### ISSUE TITLE
merge (fast forward) di memory

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#11]

**Comment by TeoColuccio** [comment]
Fatto, facile facile. Ovviamente mi sono messo su master e ho fatto il
merge con memory, ma se faccio il contrario che succede?

2015-12-30 17:01 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Haha un casino

Senti. Ora fai il merge di master con cpu. Questa volta senza rebase

Il mercoledì 30 dicembre 2015, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Fatto

Il giorno 30 dicembre 2015 18:40, Fabio Z Tessitore <
notifications@github.com> ha scritto:
