### ISSUE TITLE
fetch()

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#12]
Il ciclo di istruzione di compone di tre parti:
1. fetch
2. incremento del program counter (`instructionCounter` nel nostro esempio)
3. execute

Per prima cosa implementeremo la funzione fetch().
Deve caricare dalla memoria la prossima istruzione da eseguire (`memory[instructionCounter]`) e copiarla nel registro `instructionRegister`.
Poi deve prelevare il codice di operazione (prime due cifre) e l'operando (seconde due cifre) e memorizzarli rispettivamente in `operationCode` e `operand`.

Es.
quando inizia il programma di esempio, `instructionCounter` vale 0
quindi verrà prelevata l'istruzione 1009
Al termine della funzione fetch() i registri della cpu avranno valore:

``` c
accumulator:           +0000
instructionCounter:       00
instructionRegister:   +1009
operationCode:            10
operand:                  09
```

**Comment by TeoColuccio** [comment]
Alla funzione fetch non dovremmo passare il vettore memory, size, e i
puntatori a instructionCounter, instructionRegister, operandCode, operand?

2016-01-01 11:12 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Ottimo, tranne per instructionCounter che non viene modificato da fetch

Il venerdì 1 gennaio 2016, Teodoro777 notifications@github.com ha scritto:

**Comment by FabioZTessitore** [comment]
Non hai capito niente :)

**Comment by TeoColuccio** [comment]
Ahahah come mai?!

Il venerdì 1 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Eh, come mai? Rileggi bene cosa viene chiesto. C'è anche l'esempio. A domani
Il 02/gen/2016 12:32 AM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Memory deve avere per forza l'indice instructionCouter così come quel
valore di un determinato indice deve essere copiato in instructionRegister.
Inoltre nella seconda come scindo un numero intero? Un vettore?!

2016-01-02 0:34 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
instructionCounter è un registro della cpu e ti dice quale istruzione (**una sola**) devi prelevare dalla memoria. capito?

**Comment by TeoColuccio** [comment]
Infatti avevo provato con un solo indice e aveva funzionato, ma adesso come
scindo le 4 cifre in 2 gruppi?

Il giorno 2 gennaio 2016 16:48, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
ah,

``` c
int num = 1234;
int prime = num / 100; /* 12 */
int seconde = num % 100; /* 34 */
```

**Comment by FabioZTessitore** [comment]
ma `i` che c'entra? come te lo devo spiegare che l'indice di istruzione è `instructionCounter`?

**Comment by TeoColuccio** [comment]
Avevo messo i per comodità. Ora credo vada bene

2016-01-02 17:37 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Che c'entra la comodità? Azzeravi sempre instructionCounter, ad ogni
chiamata a fetch() ed è un errore

Il sabato 2 gennaio 2016, Teodoro777 notifications@github.com ha scritto:

**Comment by FabioZTessitore** [comment]
forse non hai fatto il push

**Comment by TeoColuccio** [comment]
Infatti non aveva funzionato il push.. Comunque credo di non aver ancora
capito bene in che senso una "sola instruzione". Avevo azzerato conta per
rappresentare "una sola" instruzione, ovvero quella con indice 0.

2016-01-02 21:36 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ok, ma l'indice c'è già. E' instructionCounter. Non deve crearlo fetch()

**Comment by TeoColuccio** [comment]
Allora così dovrebbe andare
