### ISSUE TITLE
incrementare l'instructionCounter

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#13]
ps. ho riorganizzato la funzione main(), quindi fai un pull

Dopo aver caricato l'istruzione in memoria (fase di fetch), il processore incrementa l'indice di istruzione (nel nostro caso instructionCounter)

**Comment by TeoColuccio** [comment]
Deve incrementare nel main, non in fetch

**Comment by FabioZTessitore** [comment]
si

2016-01-03 0:24 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by TeoColuccio** [comment]
Quindi deve fare più volte la fetch e deve stampare più volte i valori di
cpu

2016-01-03 0:26 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Al termine fetch ed esecuzione vanno in un ciclo. Al momento il ciclo non
ci interessa. Stiamo ancora creando le funzioni

Quindi, dopo aver chiamato fetch, incrementa instructionCounter.
Poi bisogna creare la funzione execute() che esegue l'istruzione
precedentemente caricata

Il domenica 3 gennaio 2016, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Allora basta che faccio instructionCounter ++ dopo fetch
Il 03 gen 2016 11:22, "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Haha si

Il domenica 3 gennaio 2016, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Fatto
