### ISSUE TITLE
Execute

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#14]
La funzione execute deve svolgere il suo compito in base al valore memorizzato in operationCode.
Ad esempio, la prima istruzione del programma è una READ, legge un valore e lo memorizza nella locazione di memoria indicata da operand

**Comment by TeoColuccio** [comment]
Quindi devo passargli solo operationCode e il vettore della memoria

**Comment by FabioZTessitore** [comment]
Qualcosa in più. Comincia a fare e vedi man mano
Il 03/gen/2016 06:31 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Ah già, ci vogliono tutte le variabili della cpu e il vettore memory. Ora credo di aver capito... Verrà bella lunghetta visto che devo scrivere cosa deve fare per ogni operatore

**Comment by FabioZTessitore** [comment]
Eh si. Comincia a fare READ e WRITE e vediamo
Il 03/gen/2016 06:39 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
La read prevede uno scanf

**Comment by FabioZTessitore** [comment]
Eh
Il 03/gen/2016 06:44 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Ho caricato un codice

**Comment by FabioZTessitore** [comment]
I codici di operazione vanno inseriti sotto forma di costanti. define va benissimo.

L'operazione WRITE è errata

**Comment by TeoColuccio** [comment]
Era errata perchè avevo messo 20 al posto di 11 come codice o altro?

Il giorno 3 gennaio 2016 22:24, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
A parte il codice operazione (che cmq va sostituito con la relativa
costante) è sbagliata l'operazione

Il domenica 3 gennaio 2016, Teodoro777 notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
la aggiustiamo la riga 133?

**Comment by TeoColuccio** [comment]
Non ho capito dov'è l'errore, ho aggiunto un \n dopo %d.. forse questo..

2016-01-04 14:08 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
no no, è un errore sostanziale. Rileggiti cosa fa WRITE

2016-01-04 14:56 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by TeoColuccio** [comment]
Ahah mo credo vada bene..

2016-01-04 14:57 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ok
adesso sostituisci le if-else if con una bella switch e poi passa alle altre operazioni

**Comment by TeoColuccio** [comment]
Okk

2016-01-04 15:04 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Sono arrivato alle ultime 4, come salto tra le istruzioni?? Mica goto?!

Il giorno 4 gennaio 2016 15:05, Teodoro Coluccio <teodoro.coluccio@gmail.com

**Comment by FabioZTessitore** [comment]
ma mica devi saltare tu?
è simpletron che deve saltare. Indovina come fa? Ti ricordi chi gli dice
qual è la prossima istruzione da eseguire?

Il giorno 4 gennaio 2016 15:20, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ahhh già!! instructionCounter

Il giorno 4 gennaio 2016 15:22, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by TeoColuccio** [comment]
Fatto

Il giorno 4 gennaio 2016 15:24, Teodoro Coluccio <teodoro.coluccio@gmail.com

**Comment by FabioZTessitore** [comment]
ok

l'istruzione HALT deve visualizzare il messaggio:

``` c
*** Simpletron execution terminated ***
```

**Comment by TeoColuccio** [comment]
Ok dopo aggiusto, ma per curiosità, già l'avete fatto simpletron?

Inviato da iPad

**Comment by FabioZTessitore** [comment]
si certo

**Comment by TeoColuccio** [comment]
Fico, per il momento sono molti righi però sono stati abbastanza semplici.. 

Inviato da iPad

**Comment by TeoColuccio** [comment]
Fatto

Il giorno 4 gennaio 2016 15:43, Teodoro Coluccio <teodoro.coluccio@gmail.com

**Comment by FabioZTessitore** [comment]
ok la funzione execute().

nel main invece ... ma dove l'hai invocata ???
le istruzioni vanno insieme:

``` C
fetch();
instructionCounter++;
execute();
```

Ora cerchiamo di fare un ciclo per eseguire tutto il programma memorizzato

**Comment by FabioZTessitore** [comment]
ho fatto qualche aggiustamento all'ordine delle chiamate nel main. fai un pull

**Comment by TeoColuccio** [comment]
Credevo che dovessimo stampare ogni volta, comunque ora che si fa? rebase e
merge?

2016-01-05 2:52 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
a parte la stampa, ti è chiaro il problema con l'instructionCounter?

2016-01-05 11:33 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by TeoColuccio** [comment]
In effetti non tanto, perchè non lo incrementiamo alla fine??

Il giorno 5 gennaio 2016 11:33, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
Che succede se incrementi alla fine e l'istruzione era un salto?
Il 05/gen/2016 01:10 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Credo vada un istruzione avanti

Il martedì 5 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Però così non viene eseguita l'istruzione 00...

Il martedì 5 gennaio 2016, Teodoro Coluccio teodoro.coluccio@gmail.com ha
scritto:

**Comment by FabioZTessitore** [comment]
l'istruzione 00 non c'entra. E' la prima ad essere eseguita.

Se pero' trovi un salto viene modificato il valore di instructionCounter. Se l'incremento sta dopo il salto verrà fatto alla posizione sbagliata (una in più). Mettendolo prima invece va tutto bene

**Comment by TeoColuccio** [comment]
Ok capito
