### ISSUE TITLE
rebase o merge?

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#15]
decidi tu quale vuoi usare

**Comment by TeoColuccio** [comment]
Il merge lo so fare bene, quindi faccio il rebase che per me è più difficile ahah

Inviato da iPad

**Comment by FabioZTessitore** [comment]
ok

Il giorno 5 gennaio 2016 17:20, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Al massimo per stasera lo faccio perché non sto a casa

Il martedì 5 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
figurati

**Comment by TeoColuccio** [comment]
Per il rebase NON interattivo, non mi devo posizionare su execute e dare
"git rebase master"?!?

2016-01-05 17:41 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Si si

Il martedì 5 gennaio 2016, Teodoro777 notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Bene allora non sbaglio io...[image: Immagine incorporata 1]

2016-01-05 21:31 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Non vedo l'immagine

**Comment by TeoColuccio** [comment]
Vabbè esce "Current branch execute is up to date."

2016-01-05 21:41 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Ma forse avevi già fatto un rebase che credevi non essere andato bene?
Il log che dice?
Vabbè esce "Current branch execute is up to date."

2016-01-05 21:41 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
In ogni caso il file non lo modifica affatto, allego il log e ho fatto merge

2016-01-05 22:01 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
2016-01-05 22:03 GMT+01:00 Teodoro Coluccio teodoro.coluccio@gmail.com:

**Comment by FabioZTessitore** [comment]
Guarda che dal grafico si vede che hai fatto un rebase

**Comment by TeoColuccio** [comment]
Sì ma non avev< funzionato perchè nel main del master non cambiava niente

Il giorno 5 gennaio 2016 22:19, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
ma è giusto così. quando fai il rebase di execute, il master non cambia di una virgola. Però execute adesso parte da li come storia permettendoti un fast forward quando fai il merge

Sta storia ancora non l'hai capita bene

**Comment by TeoColuccio** [comment]
Non ho capito in che senso parte da li... Non ci sono commit precedenti??

Il martedì 5 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
è come se il branch execute fosse stato creato da quel punto sul master

Il giorno 5 gennaio 2016 22:47, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Però per rendere effettive le modifiche devo fare per forza un merge??

Il martedì 5 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
si
come già ti ho spiegato facendo così il merge diventa fast forward e la
storia diventa lineare

2016-01-05 23:00 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by TeoColuccio** [comment]
OK allora tutto apposto

Il martedì 5 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:
