### ISSUE TITLE
divisione in moduli

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#16]
il simulatore è praticamente funzionante, puoi dargli in pasto un programma scritto nel suo linguaggio e lui lo esegue. Bisognerebbe creare la funzione per il caricamento del programmi all'avvio e bisognerebbe gestire gli errori, però al momento queste cose non ci interessano.

Invece bisogna individuare gli "oggetti" che compongono il nostro simulatore e creare per ognuno di essi un modulo separato.

tu quali "oggetti" vedi?

**Comment by TeoColuccio** [comment]
Se scomponiamo il simulatore potremmo avere: memoria e CPU,

Il martedì 5 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
senza dubbio

Il giorno 5 gennaio 2016 22:58, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Quindi creo delle struct?

Il martedì 5 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
bisogna creare le struct nei rispettivi file, aggiungere le funzioni
necessarie ecc ecc ecc
da dove vuoi cominciare?

2016-01-05 23:06 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by TeoColuccio** [comment]
Faccio un memory.h

2016-01-05 23:10 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Ahh ma lo faccio stesso nel master o creo un breanch?

2016-01-05 23:18 GMT+01:00 Teodoro Coluccio teodoro.coluccio@gmail.com:

**Comment by FabioZTessitore** [comment]
come preferisci, in generale sarebbe meglio creare una branch per evitare
di avere un master che non funziona

2016-01-05 23:19 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by TeoColuccio** [comment]
Visto che è gratis creo un breanch dev_memory ahah

Il giorno 5 gennaio 2016 23:22, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
haha ottimo

**Comment by TeoColuccio** [comment]
Creo memory.c

2016-01-05 23:29 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Per il momento non voglio interferire. Fai. Cerca di fare in modo che dopo
ogni modifica che ti viene in mente il programma continui a funzionare

Il martedì 5 gennaio 2016, Teodoro777 notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Ok vediamo che succede, comunque per sbaglio ho creato main.c nel master,
come lo elimino senza cancellare tutto e rifare pull?

Il giorno 5 gennaio 2016 23:37, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
Non ho capito che significa che hai creato un main.c nel master. Non c'era
già?
Cmq nel dubbio fai il clone in un'altra directory e se ok questa la cancelli
(Github ti fa da server di backup per fortuna)

Il martedì 5 gennaio 2016, Teodoro777 notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Nono scusate ho creato memory.c nel master

Il giorno 5 gennaio 2016 23:42, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
E cancellalo

Il martedì 5 gennaio 2016, Teodoro777 notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Fatto ora provo a modificare il main

Il martedì 5 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Questo mi è nuovo...

Il giorno 5 gennaio 2016 23:58, Teodoro Coluccio <teodoro.coluccio@gmail.com

**Comment by FabioZTessitore** [comment]
Prima di tutto vorrei capire perché hai cancellato dal main quasi tutto???

Riguardo alle funzioni che lavorano con la memoria ... Se passi la struct Memory, mi spieghi per quale motivo passi anche il vettore e poi la dimensione? Allo stesso modo nel main hai creato due memorie, una tramite struct (che viene passata alle funzioni, ma mai utilizzata) e una tramite vettore come facevi prima (che invece deve sparire)

**Comment by TeoColuccio** [comment]
Vabbé ho cancellato perché tanto dopo devo fare questo anche per la cpu, ma era più logico non cancellare, dopo rifaccio. 
Comunque era una bozza,  ovvio devo cancellare il vettore memory, ho fatto tutto molto veloce nel main. 
Ma alla fine le funzioni nei file .h e .c vanno bene?

Inviato da iPad

**Comment by FabioZTessitore** [comment]
no perché accettano sia un puntatore alla struct Memory che un vettore

**Comment by FabioZTessitore** [comment]
ci sono anche dei problemi con maiuscole e minuscole. stai attento

**Comment by TeoColuccio** [comment]
Ok aggiusterò 

Inviato da iPad

**Comment by TeoColuccio** [comment]
Giusto!! Che l'ho rimasto a fa il vettore anche nelle funzioni!! Non me
n'ero proprio accorto ahaha

Il mercoledì 6 gennaio 2016, Teodoro Coluccio teodoro.coluccio@gmail.com
ha scritto:

**Comment by FabioZTessitore** [comment]
però lo usi invece di usare la struct

**Comment by TeoColuccio** [comment]
No non è che lo uso, ce l'ho rimasto usato. Comunque devo passare solo la
struct della memoria in entrambi le funzioni

2016-01-06 19:35 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Credo che già così vada (molto) meglio, domani credo di finire

Il giorno 6 gennaio 2016 23:19, Teodoro Coluccio <teodoro.coluccio@gmail.com

**Comment by FabioZTessitore** [comment]
come hai fatto a cambiare il nome alla branch?

**Comment by TeoColuccio** [comment]
Ne ho creato uno nuovo ed eliminato quello di memory ahahaha

2016-01-07 16:19 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
si ok, ma non ho capito bene il grafico come esce. domani vediamo

Il giorno 7 gennaio 2016 16:20, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Okk comunque mi escono degli errori impossibili..

Il giorno 7 gennaio 2016 16:22, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
ci sono degli errori impossibili

2016-01-07 17:04 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by TeoColuccio** [comment]
Eh avete visto?

Inviato da iPad

**Comment by FabioZTessitore** [comment]
non ho compilato, ma basta guardare il codice hahaha

**Comment by TeoColuccio** [comment]
Ahah ma nel main?! Il file .h sicuro è corretto 

Inviato da iPad

**Comment by FabioZTessitore** [comment]
cpu.c fa paura

**Comment by TeoColuccio** [comment]
Apparte il reset le altre 2 stanno sbagliatissime vero?

Inviato da iPad

**Comment by FabioZTessitore** [comment]
comincia da dump

**Comment by TeoColuccio** [comment]
Si sì tra poco aggiusto tutto 

Inviato da iPad

**Comment by TeoColuccio** [comment]
Mi sono confuso n'attimo con -> e . Ahah

Inviato da iPad

**Comment by TeoColuccio** [comment]
Nel dump forse vanno i puntatori e non i punti

Il giorno 7 gennaio 2016 18:30, Teodoro Coluccio <teodoro.coluccio@gmail.com

**Comment by FabioZTessitore** [comment]
No forse. Se hai un puntatore ci vuole la freccia
Il 07/gen/2016 07:41 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Però nelle altre 2 l'ho messo il puntatore

Il giorno 7 gennaio 2016 20:09, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by TeoColuccio** [comment]
Cioè la freccia

Il giorno 7 gennaio 2016 20:55, Teodoro Coluccio <teodoro.coluccio@gmail.com

**Comment by FabioZTessitore** [comment]
Però se non metti i nomi ai parametri non c'è scampo

Il giovedì 7 gennaio 2016, Teodoro777 notifications@github.com ha scritto:

**Comment by FabioZTessitore** [comment]
la riga 29 aspetta a te ....

**Comment by TeoColuccio** [comment]
Non solo quella, ho aggiustato anche altre cose, ma comunqua sempre li
stessi errori

2016-01-07 21:46 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
no no, l'errore c'è

**Comment by TeoColuccio** [comment]
2016-01-07 21:54 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Non mi dite che sbaglio a mettere un puntatore..

2016-01-07 21:57 GMT+01:00 Teodoro Coluccio teodoro.coluccio@gmail.com:

**Comment by FabioZTessitore** [comment]
ma vuoi leggere? manca il nome del parametro

2016-01-07 21:58 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by TeoColuccio** [comment]
No scusate, cel'ho messo c dopo CpuPtr ma non ho fatto push!!

Il giorno 7 gennaio 2016 21:59, Fabio Z Tessitore notifications@github.com
ha scritto:
