### ISSUE TITLE
Simpletron in c++

### ISSUE THREAD

**Issue by TeoColuccio** [Teodoro777/simpletron#17]

**Comment by FabioZTessitore** [comment]
la prima cosa che dovresti fare è semplificare i nomi delle funzioni. es azzera_memoria può diventare azzera. Ricordati che ora non è una funzione generale, ma un metodo della classe memory.
ovviamente lo stesso vale per le altre

**Comment by TeoColuccio** [comment]
Fatto

2016-01-09 18:40 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
In CPU.h c'è memory_size

La dump stampa solo i valori senza nessuna formattazione

**Comment by TeoColuccio** [comment]
Eh deve stampare così com'è.. come ho fatto non va bene?

2016-01-10 10:56 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Non va bene perché così stampa solo una sequenza di numeri. Invece la
stampa dovrebbe essere la stessa di prima

Il domenica 10 gennaio 2016, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Credo mo vada bene, ma per non mettere tutti quei endl non posso fare \n
dopo i registri da stampare?

Il domenica 10 gennaio 2016, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
Puoi mettere i caratter '\n' ma non conviene. Ti faccio vedere

``` c++
cout << "instructionCounter: " << instructionCounter << endl;
cout << "instructionCounter: " << instructionCounter << "\n";
```

Inoltre quando devi stampare tante cose ogni tanto vai a capo. Es

``` c++
cout << "instructionCounter: " << instructionCounter << endl <<
        "instructionRegister: " << instructionRegister << endl <<
             ...;
```

**Comment by FabioZTessitore** [comment]
memory::dump fa ancora uso delle funzioni printf e putchar

**Comment by FabioZTessitore** [comment]
Mancano i costruttori agli oggetti cpu e memory. I costruttori potrebbero richiamare le funzioni di azzeramento così il main si semplifica

**Comment by TeoColuccio** [comment]
Per la chiamata nel costruttore secondo me non va bene come ho messo...

Il giorno 10 gennaio 2016 12:27, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
infatti. il membro `memory` è un array. Non puoi scrivere `memory.azzera()`

Ti basta chiamare `azzera()`

**Comment by TeoColuccio** [comment]
E non inchiamo chi deve azzerare? Se tenevamo due array come capiva quale
azzerare?

2016-01-10 12:48 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma di che parli???
sei all'interno dell'oggetto Memory che contiene un solo array. La funzione azzera() sa cosa deve farci. Punto.

Se avessi avuto un oggetto con due array avresti avuto varie funzioni per lavorarci

**Comment by TeoColuccio** [comment]
Ah ok capito

Il giorno 10 gennaio 2016 12:52, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
OK,

ora facciamo un passo avanti.

L'oggetto Cpu ha bisogno di una Memory per poter lavorare. Invece di passare un riferimento a Memory nelle varie funzioni potrebbe essere opportuno mantenere un riferimento a Memory all'interno di Cpu. In questo modo le funzioni membro di Cpu saprebbero sempre con quale memoria lavorare. Se ci pensi questo meccanismo permetterebbe anche di avere più Cpu che lavorano con la stessa Memory.

**Comment by TeoColuccio** [comment]
Ok ma come ce lo posso rimanere il riferimento a memory?

Il giorno 10 gennaio 2016 13:07, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Tra i membri privati di `Cpu` bisogna aggiungere `MemoryPtr memory`.
Il costruttore di Cpu deve accettare come parametro una Memory e fare l'associazione

Poi le varie funzioni di Cpu dovranno usare questo riferimento

**Comment by TeoColuccio** [comment]
Faccio il typedef o va bene *memory?

Il giorno 10 gennaio 2016 13:12, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Come preferisci. A me un asterisco non spaventa haha

**Comment by TeoColuccio** [comment]
Ho messo l'asterisco, quindi adesso nelle funzioni non devo passare niente
visto che memory fa parte della class

2016-01-10 13:15 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Prima di tutto `*Memory` non significa niente. Forse volevi scrivere `Memory* memory`
Inoltre si tratta di un puntatore che attualmente non punta a niente. Il costruttore di Cpu dovrebbe accettare un riferimento ad una Memory e fare l'associazione

**Comment by TeoColuccio** [comment]
Aee come lo faccio il costruttore per l'accettazione?!

Il giorno 10 gennaio 2016 14:13, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
visto che sono cose nuove per te ho fatto io qualche aggiustamento. Vedi se ti è tutto chiaro

**Comment by TeoColuccio** [comment]
OK credo di aver capito, ma se non facevamo il giochetto con il costruttore
di CPU che succedeva?

Il domenica 10 gennaio 2016, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
Non succedeva niente, i due oggetti erano slegati e saresti stato costretto a passare memory alle funzioni di cpu che ne hanno bisogno.
Le funzioni sono da intendersi come dei messaggi che invii agli oggetti. Mandare un messaggio fetch() alla cpu e fare in modo che la cpu sappia già qual è la memoria a cui fa riferimento mi sembrava più logico rispetto a mandare il messaggio fetch() e dire da quale memoria andare a prelevare

**Comment by TeoColuccio** [comment]
Ma la dovevo passare anche se era tra i membri privati ma non faceva parte
del costruttore?

Il domenica 10 gennaio 2016, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
Nei membri privati c'è solo un puntatore. Finché non gli dici a chi puntare non serve a niente

**Comment by TeoColuccio** [comment]
Ma è un puntatore ad una memory... Domani mi spiegate meglio

Il domenica 10 gennaio 2016, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
E che indirizzo contiene quando si crea una cpu?

Il domenica 10 gennaio 2016, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Della variabile m...

Inviato da iPad

**Comment by FabioZTessitore** [comment]
No. m è un puntatore di tipo Memory.
Il 10/gen/2016 11:25 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Prof ho aggiustato molte cose, ma com'è che mi dice che i membri sono
privati anche quando deve fare il controllo nel while?!?

Il giorno 10 gennaio 2016 23:33, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
perché nella condizione del ciclo fai l'accesso ai membri privati operationCode e instructionRegister della cpu c

ps. devi eliminare le righe 15 e 16

**Comment by TeoColuccio** [comment]
Si perché azzerano già i costruttori, ma quindi devo creare altre funzioni
per fare il ciclo?!

Il lunedì 11 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
ti servono un paio di get

**Comment by TeoColuccio** [comment]
Fatte le get, ma mo escono certi errori..

2016-01-11 18:50 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Il codice dovrebbe andar bene. Devi aggiustare il Makefile. Bisogna sostituire gcc con g++ e CFLAGS con CXXFLAGS

**Comment by TeoColuccio** [comment]
Perchè dobbiamo cambiare anche quella specie di variabile?!

2016-01-11 22:38 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Innanzitutto non è una specie di variabile. È una variabile.

Se ci fai caso, non viene richiamata da nessuna parte perché ci pensa make
quando fa le compilazioni (non il link).
A seconda del linguaggio usato, make usa l'una o l'altra
Il 11/gen/2016 10:42 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Ok ma comunque ci sta un errore..

Il giorno 11 gennaio 2016 22:49, Fabio Z Tessitore <notifications@github.com

**Comment by TeoColuccio** [comment]
Prof ci siete?

Il lunedì 11 gennaio 2016, Teodoro Coluccio teodoro.coluccio@gmail.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Più o meno. Non posso stare al PC ora
Il 12/gen/2016 03:45 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Okk quando potete la ci stanno degli errori indecifrabili ahah

Il martedì 12 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Errori non ce n'erano. C'era solo un warning dovuto al fatto che la stringa restituita da welcome() andava dichiarata come const.
Per il resto ho aggiustato le stampe con cout (cose che non hai studiato)

**Comment by TeoColuccio** [comment]
Ok appena posso faccio il modulo simpletron

Il martedì 12 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Domani mi spiegate quel casino con le cout

Il martedì 12 gennaio 2016, Teodoro Coluccio teodoro.coluccio@gmail.com
ha scritto:

**Comment by FabioZTessitore** [comment]
sono modificatori dell'IO. Purtroppo il C++ ha complicato molto le cose
secondo me sulla gestione dell'output a schermo. Cmq si può usare sempre la
printf del C, basta includere stdio.h come al solito

Il giorno 12 gennaio 2016 21:10, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ma se non mettevate tutte quelle cose succedeva quell'errore di
segmentazione che mi ritrovavo io?!

Il martedì 12 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
No. A me non dava nessun errore di segmentazione. Puoi provare a fare un
checkout al commit precedente e controllare

Forse avevi fatto qualche modifica in locale

Il martedì 12 gennaio 2016, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
E allora se funzionava perché avete aggiunto tutte quelle cose?

Il martedì 12 gennaio 2016, Fabio Z Tessitore notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Non ho detto che funzionava ... ho detto che non dava errori di
segmentazione. L'output era tutto sballato. Fai checkout e controlla

Il mercoledì 13 gennaio 2016, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
OK appena posso faccio il modulo simpletron.

Il mercoledì 13 gennaio 2016, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by TeoColuccio** [comment]
Ho aggiustato un pò tutto e spostato il ciclo e le set del main in
simpletron, ho cambiato il . in ->

Il giorno 13 gennaio 2016 13:47, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Gira?
Il 15/gen/2016 08:42 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
no

Il giorno 15 gennaio 2016 20:58, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Haha
Il 15/gen/2016 09:07 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Avete visto?? ahah

Il giorno 15 gennaio 2016 21:08, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Ho aggiunto il modulo simpletron al Makefile

**Comment by TeoColuccio** [comment]
E funziona mo?
Il 15 gen 2016 22:19, "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
eh certo, prova

**Comment by TeoColuccio** [comment]
Ah quindi avevo fatto bene, mancava solo nel make..
Il 15 gen 2016 22:32, "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
si si

**Comment by TeoColuccio** [comment]
Eheh alto livello
Il 15 gen 2016 22:34, "Fabio Z Tessitore" notifications@github.com ha
scritto:
