### ISSUE TITLE
Welcome() returns (no print)

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#3]
La funzione welcome dovrebbe restituire la stringa da stampare piuttosto che stamparla direttamente

**Comment by TeoColuccio** [comment]
Ci avevo pensato infatti :)..

Il domenica 20 dicembre 2015, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by TeoColuccio** [comment]
Prof ho fatto la funzione di welcome e anche quella che azzera la memoria,
ma sto trovando difficoltà nel fare quella per la stampa della tabella:
come valore di ritorno credo che ritorni un vettore che sarà quello della
memoria, stampato in un certo modo che non conosco..

2015-12-21 0:45 GMT+01:00 Teodoro Coluccio teodoro.coluccio@gmail.com:
