### ISSUE TITLE
Welcome indent

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#4]
Fix indentation

**Comment by FabioZTessitore** [comment]
come già richiesto devi aggiustare le indentazioni.
con vim prova a fare così

ggVG=

che significa
gg -> vai a inizio file
V -> modo visuale linea
G -> fine del file
(a questo punto hai tutto il file selezionato)
= -> aggiusta l'indentazione

**Comment by TeoColuccio** [comment]
Forte questa funzione!

Il giorno 21 dicembre 2015 18:23, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
anche welcome richiede
