### ISSUE TITLE
welcome message

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#5]
il messaggio di benvenuto definitivo

![welcome](https://cloud.githubusercontent.com/assets/3002194/11936845/d3ee3810-a810-11e5-9856-6d7b7c049663.png)

**Comment by TeoColuccio** [comment]
Ho fatto, ma di sicuro c'è un modo per farlo più ordinato (e leggibile) di
come ho fatto io.

Il giorno 21 dicembre 2015 18:30, Fabio Z Tessitore <
notifications@github.com> ha scritto:
