### ISSUE TITLE
memory dump

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#6]
il dump della memoria deve venire così

![memory](https://cloud.githubusercontent.com/assets/3002194/11936925/54344c76-a811-11e5-94af-9b6783ceda59.png)

**Comment by FabioZTessitore** [comment]
la funzione memory_dump() accetta il vettore memory e stampa così come mostrato

**Comment by TeoColuccio** [comment]
Ora viene il bello

2015-12-21 22:13 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
La funzione non dovrebbe tornare nulla in quanto stamperà con un normale
printf giusto?

Il giorno 22 dicembre 2015 12:08, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Si si
Il 22/dic/2015 02:45 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Non so come utilizzare il printf per stampare in questo modo

2015-12-22 15:57 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
non dire così che i cicli li sai fare

**Comment by TeoColuccio** [comment]
Ahah si però non so come si stampa a 4 elementi alla volta

2015-12-23 17:17 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
non sono 4 elementi. E' una sola cella di memoria stampata con %+04d

**Comment by TeoColuccio** [comment]
Ho scritto in questo modo, ma a partire dalla seconda riga della prima
colonna ho solo 3 zero.

Il giorno 23 dicembre 2015 18:05, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
non diventano 3 gli zeri. Il quarto sta sulla riga precedente.
Ricordati che dopo aver stampato 10 elementi devi andare a capo.
Inoltre le celle di memoria vanno stampate con il segno %+04d

**Comment by TeoColuccio** [comment]
Come faccio ad andare a capo proprio dopo 10 elementi?

Il giorno 24 dicembre 2015 11:42, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Non ti rispondo

Il giovedì 24 dicembre 2015, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ahah so che è facile, ma non mi riesce al momento..

Il giorno 24 dicembre 2015 12:58, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ho fatto una modifica.
ora bisogna aggiungere le intestazioni alla tabella.

ps i valori della memoria vanno stampati con il segno (cerca di capire come si fa e come modificare il codice)

**Comment by TeoColuccio** [comment]
Ho capito quello che avete fatto, per l'intestazione ho messo solo "memory:
".

Il giorno 24 dicembre 2015 13:54, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
le altre intestazioni ti stavano antipatiche?

**Comment by TeoColuccio** [comment]
Devo mettere anche i numeri su righe e colonne?

Il giovedì 24 dicembre 2015, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
come la figura sopra

**Comment by TeoColuccio** [comment]
Buon Natale prof, continuo domani perché non sono stato un attimo a casa 

Inviato da iPad

**Comment by FabioZTessitore** [comment]
buon natale anche a te

Il giorno 25 dicembre 2015 18:53, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ho fatto la bozza, devo trovare la posizione giusta dove stampare righe e
colonne.

Il giorno 25 dicembre 2015 18:56, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Non riesco a trovare una soluzione, stampa sempre prima la matrice e poi le
celle di memoria.

Il giorno 26 dicembre 2015 12:29, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
A parte il fatto che confondi righe e colonne ...
cmq mentre le intestazioni di colonna le devi stampare prima della matrice,
quelle di riga vanno stampate contestualmente alla riga stessa
Il 26/dic/2015 05:39 PM, "Teodoro777" notifications@github.com ha scritto:

**Comment by TeoColuccio** [comment]
Prof ma adesso dove sbaglio? Nel primo ciclo stampo le colonne e ok. Nel
secondo stampa la riga, stampa le dieci celle tabulando a destra, e ogni 10
celle va a capo..

Il giorno 26 dicembre 2015 17:44, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
avevi fatto un ciclo sulle righe da farsi 10 volte a **al suo interno** un ciclo sugli elementi della memoria

**Comment by TeoColuccio** [comment]
Sì ora ho capito

Il giorno 26 dicembre 2015 21:11, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Però in che si differenziano i due "if"?

Il giorno 26 dicembre 2015 23:03, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
i%10==0 quando i vale 0, 10, 20 ecc, cioè quando inizia una riga

(i+1)%10==0 quando i vale 9, 19, 29 ecc cioè fine riga

Il sabato 26 dicembre 2015, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Giusto.

Il giorno 26 dicembre 2015 23:14, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ora che si fa?

Inviato da iPad

**Comment by FabioZTessitore** [comment]
prima di proseguire con il codice vorrei farti vedere come semplificare la
storia dei commit.
c'è modo di fare una chat?

Il giorno 27 dicembre 2015 00:19, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Certo! Tramite mail?

Inviato da iPad
