### ISSUE TITLE
merge welcome

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#7]
welcome è pronto per il merge con il master

**Comment by TeoColuccio** [comment]
Fatto. Ho usato per la prima volta il mio (ultimo rimasto) computer windows
per lavorare su git, al posto di usare una macchina virtuale con virtual
box ho usato cloud9 ide. E' anche meglio di una virtual box

2015-12-21 22:14 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
mi spieghi cosa hai fatto? non vedo nessun merge

**Comment by TeoColuccio** [comment]
Sono passato nel master e ho fatto git merge welcome e poi ho fatto il
commit e push. Io lo vedo il welcome nel master

2015-12-22 10:46 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Il commit non è necessario perché il merge lo fa automaticamente. Nel
master vedo le modifiche ma non ci sono commit

Il martedì 22 dicembre 2015, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ma i comandi quelli sono, giusto?

2015-12-22 10:55 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
secondo me è successo che avendo fatto il merge tempo fa per errore, in realtà welcome e master sono la stessa branch
