### ISSUE TITLE
modello cpu

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#8]
creiamo un modello di cpu.

dovranno essere presenti i seguenti registri:
- accumulator
- instructionCounter
- instructionRegister
- operationCode
- operand

inoltre bisogna creare una funzione per il dump di questi registri il cui output sia:
![dump_cpu](https://cloud.githubusercontent.com/assets/3002194/12036472/812b5b94-ae46-11e5-91ca-7e84d3cb5b11.png)

**Comment by TeoColuccio** [comment]
I registri di che tipo li dichiaro, int va bene?

2015-12-29 16:10 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
si si, sono tutti int

2015-12-29 16:58 GMT+01:00 Teodoro777 notifications@github.com:

**Comment by FabioZTessitore** [comment]
non capisco quelle virgole nella printf
Inoltre una delle variabili viene azzerata prima di essere stampata, non ha senso

**Comment by TeoColuccio** [comment]
Ahah no le virgole sono inutili e la variabile l'avevo azzerata per un
esperimento, nel prossimo push aggiusto.

Il giorno 29 dicembre 2015 20:15, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Ci ho messo un pò per caricarlo perchè mi dava uno strano errore ed ho
risolto cancellando e rifacendo il pull.

Il giorno 29 dicembre 2015 20:20, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Si. Forse perché ho cancellato un file su github. Devi sempre fare pull
finché sono collaboratore hihihi

Il martedì 29 dicembre 2015, Teodoro777 notifications@github.com ha
scritto:

**Comment by TeoColuccio** [comment]
Ma infatti l'avevo pensato Ahah. Comunque credo vada bene il programma (mo
era facile veramente).

Il martedì 29 dicembre 2015, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
nella stampa mancano i nomi dei registri

**Comment by TeoColuccio** [comment]
Aggiustato

2015-12-29 22:10 GMT+01:00 Fabio Z Tessitore notifications@github.com:
