### ISSUE TITLE
rebase interattivo

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/simpletron#9]
sia il ramo master che il ramo cpu devono essere semplificati. un solo commit può bastare

**Comment by TeoColuccio** [comment]
Fatto

2015-12-29 22:13 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by TeoColuccio** [comment]
Ora li ho capiti bene i rebase interattivi

2015-12-29 23:42 GMT+01:00 Teodoro Coluccio teodoro.coluccio@gmail.com:

**Comment by FabioZTessitore** [comment]
diciamo bene, però il tuo main.c nel master è tornato come prima un caos. (avevi cancellato la directory e rifatto il clone vero???)

**Comment by FabioZTessitore** [comment]
ora te lo riaggiusto, stai fermo

**Comment by FabioZTessitore** [comment]
fatto, **CANCELLA** la tua directory e rifai il clone **ORA**

**Comment by TeoColuccio** [comment]
Ok ma pechè stava il caos?

2015-12-29 23:47 GMT+01:00 Fabio Z Tessitore notifications@github.com:
